name: CI # Workflow ka name:cite[1]

on: # Workflow kab run hoga:cite[5]
  push: # Jab naya code push karenge
    branches: [ main ] # 'main' branch mein push karne par
  pull_request: # Ya jab koi naya Pull Request banaye
    branches: [ main ] # 'main' branch ke liye
  workflow_dispatch: # Manual run ka option:cite[1]

jobs:
  build: # Job ka name
    runs-on: ubuntu-latest # Job kis environment mein run hoga:cite[1]

    steps: # Job ke steps
      # Step 1: Repository ka code check-out karna
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Node.js environment set karna
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Apna bot kis Node.js version par chal raha hai

      # Step 3: Dependencies install karna
      - name: Install dependencies
        run: npm ci

      # Step 4: Security audit karna
      - name: Run security audit
        run: npm audit --audit-level moderate

      # Step 5: Basic syntax check karna
      - name: Check syntax
        run: |
          node -c bot/login/login.js
          node -c utils.js
